### ISSUE TITLE
Chrome is busy when text is selected

### ISSUE THREAD

**Issue by pim-pesochek** [bootlin/elixir#83] opened 2019-12-25 14:10 UTC
Hello there!
Not sure if I choose the right place to submit an issue related to elixir.bootling.com (if I am wrong, please delete it or close)
I start having issues under chrome browser when I do text selection. Here are the steps to reproduce it:
1. Open tab in chrome and paste in address line https://elixir.bootlin.com/linux/v4.12.14/source/drivers/gpu/drm/drm_drv.c#L158
2. Hold Left button on mouse and try to select some lines
3. Chrome browser starts loading cpu for 100% and highlighting is freezing.

Chrome Version 79.0.3945.88 (Official Build) (64-bit)
OS: macOS Catalina 10.15.1 (19B88)

**Comment by heddev** [comment] 2019-12-28 12:05
This is also happening with most of the big files with both mobile and desktop. Once i tap/click on the page after it load, even without selecting text, the page freezes. Example file kernel/module.c.

Mobile ver 79.0.3945.93

**Comment by SPYFF** [comment] 2019-12-28 15:49
Same here. Even with smaller files and on a fairly strong CPU, scrolling freezes.

**Comment by pim-pesochek** [comment] 2020-01-09 15:27
@SPYFF maybe it is related to Chrome.
I have updated to version 79.0.3945.117 and scroll freezing disappeared, however selection/deselection still quite slow

**Comment by michaelopdenacker** [comment] 2020-01-30 13:56
Hi,
Many thanks for the report.
However, I didn't manage to reproduce the issue with Chromium on Ubuntu on x86-64 -  Version 79.0.3945.130 (Official Build) snap (64-bit)
I guess that the bug has been fixed in the browser since then.
Thanks again,
Michael

**Closed by michaelopdenacker** 2020-01-30 13:56 UTC
