### ISSUE TITLE
Line Numbers and Code Offset

### ISSUE THREAD

**Issue by zvargas** [bootlin/elixir#210] opened 2021-02-16 16:01 UTC
I am seeing what I believe to be the same issue reported in #46 - where line numbers are increasingly offset from the associated line of code. Here is a screen shot of what I see on Windows with Chrome 88.0.4324.150:
![elixir_linenum_offset](https://user-images.githubusercontent.com/23265563/108066725-58bfd580-7025-11eb-8c91-f9cd72b91b32.PNG)

I have seen a similar offset before on Linux (Ubuntu 20.04) but was not able to reproduce it with the latest Firefox or Chrome. The issue presents on long files (with lots of lines) and appears to be a small mismatch between  the line numbers and the code content.

My understanding of the problem is that the computed value of `line-height` varies based on the rounding algorithm used by a browser. For example, in the environment from the screenshot, `line-height` is calculated as `17.28px`. In cases where I do not see this offset the calculated `line-height` is `17.2833px`. However, I can't explain why there is an offset because both columns report the same calculated value.

I was able to 'fix' the offset by setting `line-height` (http/style.css line65) to a whole number or the keyword `normal`.

**Comment by fstachura** [comment] 2024-06-05 13:58
Closing - a fix was merged, cannot reproduce the bug in the file from the screenshot anymore.

**Closed by fstachura** 2024-06-05 13:58 UTC
