### ISSUE TITLE
Error referencing some files

### ISSUE THREAD

**Issue by manasghandat** [bootlin/elixir#347] opened 2024-10-17 22:57 UTC
Cannot view some files like https://elixir.bootlin.com/linux/v6.11.3/source/fs/exec.c

**Comment by fstachura** [comment] 2024-10-18 20:49
This seems to be a duplicate of #328, the error is now gone. Please comment if the issue persists.

**Closed** 2024-10-18 20:49 UTC

**Comment by tleb** [comment] 2024-10-21 15:33
Can confirm from the logs: both errors on `/linux/v6.11.3/source/fs/exec.c` happened 13 and 19 minutes after indexing started. They have the same trace as in #328.
