### ISSUE TITLE
Struct page not found in Elixir. 

### ISSUE THREAD

**Issue by 138bit** [bootlin/elixir#207] opened 2021-01-08 13:34 UTC
When searching for struct page, nothing is found:
https://elixir.bootlin.com/linux/v4.19/A/ident/page

The struct is available in:
https://elixir.bootlin.com/linux/v4.19/source/include/linux/mm_types.h#L70

**Comment by MaximeChretien** [comment] 2021-01-08 13:45
For some reasons "page" is in the elixir blacklist, maybe this name is too much used in the source code so it creates too much entries in the database and don't give a really useful result when you search for it.

See : https://github.com/bootlin/elixir/blob/master/lib.py#L133

**Comment by michaelopdenacker** [comment] 2021-01-08 13:59
Hi,
Thanks for raising this issue to our attention.
Maxime is right about the cause of this (thanks!)
However, I'll remove this structure from the Linux blacklist, as this is an important structure to understand Linux kernel code.
Thanks again!
Michael.

**Comment by michaelopdenacker** [comment] 2021-01-08 14:06
Keeping this issue open until a new version of the database is up on https://elixir.bootlin.com/

**Comment by 138bit** [comment] 2022-10-21 10:28
The struct is available, I think this issue can close. Thanks for whitelisting it.

**Comment by fstachura** [comment] 2024-06-05 13:36
Closing - page was removed from the blacklist and the database was regenerated.

**Closed by fstachura** 2024-06-05 13:36 UTC
