### ISSUE TITLE
query.py: Need a bytes-like object

### ISSUE THREAD

**Issue by cxw42** [bootlin/elixir#82] opened 2019-12-19 21:37 UTC
I am at commit a66996d3987a9b30a0755338e582ee071c1cac7d, following the instructions in the README.  I shallow-cloned the last month of kernel history and indexed it.  When I run the sample queries, I get:

    $ ./query.py file v5.4 /kernel/sched/clock.c
    Traceback (most recent call last):
      File "./query.py", line 186, in <module>
        sys.stdout.buffer.write(output)
    TypeError: a bytes-like object is required, not 'str'
    $ ./query.py ident v5.4 raw_spin_unlock_irq
    Traceback (most recent call last):
      File "./query.py", line 186, in <module>
        sys.stdout.buffer.write(output)
    TypeError: a bytes-like object is required, not 'tuple'

If I change the last line of query.py to:

    try:                           
        sys.stdout.buffer.write(output)
    except:
        print(output)

the `file` query succeeds, and the `ident` query outputs:

    ([<__main__.SymbolInstance object at 0x7f0c989179b0>], [<__main__.SymbolInstance object at 0x7f0c98917ac8>, ..., <__main__.SymbolInstance object at 0x7f0c95f83160>, <__main__.SymbolInstance object at 0x7f0c95f83198>])

(`...` representing lots of other `SymbolInstance object` entries).

What am I missing?  Thank you!

**Comment by michaelopdenacker** [comment] 2019-12-20 09:03
Hi Chris,

Oops, query.py as a script to use from the command line is currently broken, because of changes required to support the REST API. @carmeli-tamir and @pokazef have plans to restore the old command-line API, probably through a new front-end on top of query.py.

If you have time, you could look at api.py and see how it's implemented, and help with the effort to restore the command line interface if you're interested. 

Closing this bug as this is currently expected behavior.
I'll fix the documentation though.

Thanks!
Michael.

**Closed by michaelopdenacker** 2019-12-20 09:03 UTC

**Comment by cxw42** [comment] 2020-01-02 18:20
Is #84 the beginning of the work you mentioned in your comment?

**Comment by michaelopdenacker** [comment] 2020-01-03 10:05
Right. It's merged so don't hesitate to start testing :)
Cheers,
Michael
